/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2013-12-21 10:32:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.back.wechattype;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wechattype_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/back/includ/nav-incl.jsp", Long.valueOf(1387621604000L));
    _jspx_dependants.put("/WEB-INF/back/includ/page-incl.jsp", Long.valueOf(1387621884000L));
    _jspx_dependants.put("/WEB-INF/back/includ/foot-incl.jsp", Long.valueOf(1387621761000L));
    _jspx_dependants.put("/WEB-INF/back/includ/left-incl.jsp", Long.valueOf(1387621698000L));
    _jspx_dependants.put("/WEB-INF/back/includ/res-incl.jsp", Long.valueOf(1387618414000L));
    _jspx_dependants.put("/WEB-INF/back/includ/el-incl.jsp", Long.valueOf(1387610365000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\"/>\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t<title>微盒子管理后台</title>\n");
      out.write("\t");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/css/bootstrap.min.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/css/bootstrap-responsive.min.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/css/ui-lightness/jquery-timepicker.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/css/ui-lightness/jquery-ui-datepicker.min.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/back/default.css\"></link>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-1.9.1.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery.form.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-timepicker.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/jquery-ui-datepicker.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/common/js/bootstrap.min.js\"></script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 导航条开始 -->\n");
      out.write("\t");
      out.write("\n");
      out.write("    <div class=\"navbar navbar-fixed-top\">\n");
      out.write("\t\t<div class=\"navbar-inner\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<a class=\"brand\" href=\"###\">微盒子管理后台</a>\n");
      out.write("\t\t\t\t<ul class=\"nav\">\n");
      out.write("\t\t\t\t\t<li><a href=\"###\">首页</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<a type=\"button\" class=\"btn btn-primary pull-right\">退出</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<!-- 正文内容开始 -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<!-- 左侧导航 -->\n");
      out.write("\t\t");
      out.write("\n");
      out.write("<div class=\"span3\">\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs nav-stacked\">\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"###\">微信服务帐号类型管理</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"###\">流量套餐管理</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>");
      out.write("\n");
      out.write("\t\t<div class=\"span8 radius-div\">\n");
      out.write("\t\t\t<div class=\"page-header\">\n");
      out.write("\t\t\t\t<h5>服务帐号类型管理</h5>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<a href=\"###\" class=\"btn btn-primary\">添加帐号类型</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<table class=\"table table-bordered table-hover\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th>名称</th>\n");
      out.write("\t\t\t\t\t\t<th>操作</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>IT</td>\n");
      out.write("\t\t\t\t\t\t<td><a href=\"###\"><i class=\"icon-pencil\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t<a href=\"###\"><i class=\"icon-remove\"></i></a></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t\t<!-- 分页 -->\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("<div class=\"pagination\" style=\"text-align: right;\">\n");
      out.write("\t\t\t\t\t<span>1/5页</span>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"###\">&lt;&lt;</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"###\">1</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"###\">2</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"###\">&gt;&gt;</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- 页脚开始 -->\n");
      out.write("\t");
      out.write("\n");
      out.write("<div class=\"footer\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<p>Copyright @ walker.com</p>\n");
      out.write("\t\t\t<p>Powered by 行者</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
