/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-01-05 09:20:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\"/>\n");
      out.write("\t<title>微盒子管理后台</title>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/css/bootstrap.min.css\"></link>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/css/bootstrap-responsive.min.css\"></link>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/back/default.css\"></link>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/common/js/jquery-1.9.1.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<form class=\"form form-horizontal\">\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t<label class=\"control-label\">用户名</label>\n");
      out.write("\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"username\" placeholder=\"请输入你的用户名\"></input>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t<label class=\"control-label\">密码</label>\n");
      out.write("\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"password\" placeholder=\"请输入你的密码\"></input>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t<div class=\"alert-error hide\" id=\"json-error\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"jumpUrl\" value=\"/back/flowsolution/list.do\"></input>\n");
      out.write("\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"登录\" id=\"login-btn\" class=\"btn btn-primary\"></input>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(\"#login-btn\").click(function(){\n");
      out.write("\t\t\tvar loginurl = \"/backuser/login.do\";\n");
      out.write("\t\t\tvar username = $(\"#username\").val();\n");
      out.write("\t\t\tvar password = $(\"#password\").val();\n");
      out.write("\t\t\tvar jumpurl = $(\"#jumpUrl\").val();\n");
      out.write("\t\t\tvar $jsonerror = $(\"#json-error\");\n");
      out.write("\t\t\t$jsonerror.addClass(\"hide\");\n");
      out.write("\t\t\tif(null == username || \"\" == username) {\n");
      out.write("\t\t\t\t$jsonerror.html(\"用户名为空\");\n");
      out.write("\t\t\t\t$jsonerror.removeClass(\"hide\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(null == password || \"\" == password) {\n");
      out.write("\t\t\t\t$jsonerror.html(\"密码为空\");\n");
      out.write("\t\t\t\t$jsonerror.removeClass(\"hide\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype:\"post\",\n");
      out.write("\t\t\t\turl:loginurl,\n");
      out.write("\t\t\t\tdata:{\"userName\":username,\"password\":password,\"jumpUrl\":jumpurl},\n");
      out.write("\t\t\t\tsuccess:function(mesg) {\n");
      out.write("\t\t\t\t\tif(mesg.code) {\n");
      out.write("\t\t\t\t\t\tlocation.href = mesg.jumpUrl;\n");
      out.write("\t\t\t\t\t}else {\n");
      out.write("\t\t\t\t\t\t$jsonerror.html(mesg.msg);\n");
      out.write("\t\t\t\t\t\t$jsonerror.removeClass(\"hide\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
